#!/bin/bash

etc/infrastructure/mysql/wait-for-connection

php bin/console doctrine:database:create --if-not-exists --env=test
php bin/console doctrine:migrations:migrate --no-interaction --env=test

php-fpm
